-- =====================================================================
-- V202: Phân quyền theo trang/nút + phạm vi dữ liệu của vai trò.
--
-- Bổ sung ngoài SDD gốc, đã xác nhận với người dùng 2026-09-30 (bảng
-- "Sidebar theo vai trò" đã chốt Q1–Q9 + 5 quy tắc sidebar):
--   1. roles.data_scope: vai trò được xem dữ liệu của tất cả điểm trường
--      (ALL) / chỉ điểm trường mình phụ trách (SITE) / chỉ lớp mình dạy
--      (CLASS). SELF dành cho 3 vai trò Portal (dữ liệu theo quan hệ
--      học sinh–phụ huynh–trường liên kết, không dùng phạm vi này).
--      Thay cho việc code tự đoán phạm vi theo mã vai trò.
--   2. Thêm 2 vai trò hệ thống: Kế toán (ACCOUNTANT), Tư vấn tuyển sinh
--      (CONSULTANT); đổi tên hiển thị STAFF thành "Giáo vụ" (mã giữ nguyên).
--   3. Mỗi mục sidebar có 1 mã quyền "xem trang" (tick mục = hiện menu);
--      tách academic.class.manage thành quyền theo từng nút (ghi danh, gán
--      giáo viên, xếp/sinh/nhập/dời/hủy lịch...).
--   4. Đặt lại quyền mặc định của 10 vai trò (trừ Portal) cho đúng bảng đã
--      chốt, chỉ trên các mã quyền thuộc bảng (managed). Các mã ngoài bảng
--      (ngân hàng câu hỏi, luyện Nghe-Nói, kế hoạch giảng dạy, danh mục
--      quyền...) giữ nguyên như cũ.
--   5. Ban giám đốc được thao tác như Quản trị viên (Q4); Quản trị viên có
--      mọi quyền.
--
-- Lưu ý: bước 4 GHI ĐÈ mọi chỉnh tay trước đó trên màn "Nhóm vai trò" đối
-- với các mã thuộc bảng (VD Giáo viên đang được cấp academic.class.manage
-- sẽ mất quyền ghi danh/gán giáo viên — đúng theo quyết định Q9).
-- academic.class.manage không còn được code dùng, bỏ khỏi mọi vai trò; giữ
-- lại dòng trong bảng permissions vì còn khoá ngoại từ nhật ký/ngoại lệ.
-- =====================================================================

ALTER TABLE roles ADD COLUMN IF NOT EXISTS data_scope VARCHAR(10) NOT NULL DEFAULT 'ALL'
    CONSTRAINT roles_data_scope_check CHECK (data_scope IN ('ALL', 'SITE', 'CLASS', 'SELF'));

INSERT INTO roles (code, name, description, is_system) VALUES
('ACCOUNTANT', 'Kế toán', 'Nắm học phí, hoá đơn, học bổng và thu chi.', TRUE),
('CONSULTANT', 'Tư vấn tuyển sinh', 'Quản lý lead, tư vấn và chuyển lead thành học viên.', TRUE)
ON CONFLICT (code) DO NOTHING;

UPDATE roles SET name = 'Giáo vụ', description = 'Hồ sơ học sinh, phụ huynh, trạng thái học tập, phòng học.' WHERE code = 'STAFF';
UPDATE roles SET data_scope = 'CLASS' WHERE code = 'TEACHER';
UPDATE roles SET data_scope = 'SITE' WHERE code = 'SITE_MANAGER';
-- Giáo vụ (STAFF), Tư vấn tuyển sinh (CONSULTANT): tạm để ALL (đã xác nhận với người dùng 2026-09-30)
-- vì hệ thống chưa có chỗ gán các vai trò này vào điểm trường (site_managers chỉ có SITE_MANAGER/
-- PARTNER_REP); đổi sang SITE khi có chức năng gán nhân sự vào điểm trường.
UPDATE roles SET data_scope = 'SELF' WHERE code IN ('STUDENT', 'PARENT', 'PARTNER_REP');

INSERT INTO permissions (code, name, module, description) VALUES
('academic.attendance.view', 'Xem điểm danh, báo cáo chuyên cần', 'ACADEMIC', 'V202 — phân quyền theo trang/nút'),
('academic.class-session.cancel', 'Hủy buổi học', 'ACADEMIC', 'V202 — phân quyền theo trang/nút'),
('academic.class-session.create', 'Xếp buổi học', 'ACADEMIC', 'V202 — phân quyền theo trang/nút'),
('academic.class-session.generate', 'Sinh lịch buổi học hàng loạt', 'ACADEMIC', 'V202 — phân quyền theo trang/nút'),
('academic.class-session.import', 'Nhập lịch buổi học từ Excel', 'ACADEMIC', 'V202 — phân quyền theo trang/nút'),
('academic.class-session.reschedule', 'Dời lịch, đổi phân công buổi học', 'ACADEMIC', 'V202 — phân quyền theo trang/nút'),
('academic.class.create', 'Tạo lớp học', 'ACADEMIC', 'V202 — phân quyền theo trang/nút'),
('academic.class.enrollment.create', 'Ghi danh học sinh vào lớp', 'ACADEMIC', 'V202 — phân quyền theo trang/nút'),
('academic.class.enrollment.import', 'Ghi danh học sinh theo lô', 'ACADEMIC', 'V202 — phân quyền theo trang/nút'),
('academic.class.enrollment.withdraw', 'Rút học sinh khỏi lớp', 'ACADEMIC', 'V202 — phân quyền theo trang/nút'),
('academic.class.promote', 'Chuyển lớp hàng loạt', 'ACADEMIC', 'V202 — phân quyền theo trang/nút'),
('academic.class.teacher.assign', 'Gán, đổi, kết thúc giáo viên phụ trách lớp', 'ACADEMIC', 'V202 — phân quyền theo trang/nút'),
('academic.class.update', 'Sửa hồ sơ lớp học', 'ACADEMIC', 'V202 — phân quyền theo trang/nút'),
('academic.class.view', 'Xem lớp học', 'ACADEMIC', 'V202 — phân quyền theo trang/nút'),
('academic.comment.view', 'Xem nhận xét học viên', 'ACADEMIC', 'V202 — phân quyền theo trang/nút'),
('academic.curriculum.customize', 'Tạo bản tùy biến khung chương trình cho điểm trường', 'ACADEMIC', 'V202 — phân quyền theo trang/nút'),
('academic.curriculum.view', 'Xem khung chương trình', 'ACADEMIC', 'V202 — phân quyền theo trang/nút'),
('academic.entrance.view', 'Xem kết quả đánh giá đầu vào', 'ACADEMIC', 'V202 — phân quyền theo trang/nút'),
('academic.grade.book.view', 'Xem trang Sổ điểm hệ thống', 'ACADEMIC', 'V202 — phân quyền theo trang/nút'),
('academic.grade.entry', 'Nhập, sửa điểm và gửi duyệt', 'ACADEMIC', 'V202 — phân quyền theo trang/nút'),
('academic.grade.view', 'Xem sổ điểm', 'ACADEMIC', 'V202 — phân quyền theo trang/nút'),
('academic.my-timetable.view', 'Xem lịch dạy của mình', 'ACADEMIC', 'V202 — phân quyền theo trang/nút'),
('academic.year.manage', 'Quản lý năm học, học kỳ', 'ACADEMIC', 'V202 — phân quyền theo trang/nút'),
('crm.lead.import', 'Nhập học theo lô từ trường liên kết', 'CRM', 'V202 — phân quyền theo trang/nút'),
('crm.lead.view', 'Xem danh sách lead', 'CRM', 'V202 — phân quyền theo trang/nút'),
('dashboard.view', 'Xem bảng điều khiển', 'SYSTEM', 'V202 — phân quyền theo trang/nút'),
('facility.feedback.resolve', 'Xử lý ý kiến phản hồi', 'FACILITY', 'V202 — phân quyền theo trang/nút'),
('facility.feedback.view', 'Xem ý kiến phản hồi', 'FACILITY', 'V202 — phân quyền theo trang/nút'),
('facility.room.view', 'Xem phòng học và thiết bị', 'FACILITY', 'V202 — phân quyền theo trang/nút'),
('facility.site.view', 'Xem điểm trường và hợp đồng liên kết', 'FACILITY', 'V202 — phân quyền theo trang/nút'),
('finance.expense.view', 'Xem đề nghị chi', 'FINANCE', 'V202 — phân quyền theo trang/nút'),
('finance.invoice.view', 'Xem hoá đơn', 'FINANCE', 'V202 — phân quyền theo trang/nút'),
('hrm.attendance-site.manage', 'Thêm, sửa địa điểm chấm công', 'HRM', 'V202 — phân quyền theo trang/nút'),
('hrm.attendance-site.view', 'Xem địa điểm chấm công', 'HRM', 'V202 — phân quyền theo trang/nút'),
('hrm.attendance.self', 'Chấm công cá nhân', 'HRM', 'V202 — phân quyền theo trang/nút'),
('hrm.department.view', 'Xem phòng ban và chức vụ', 'HRM', 'V202 — phân quyền theo trang/nút'),
('hrm.leave.approve', 'Duyệt, từ chối đơn nghỉ phép', 'HRM', 'V202 — phân quyền theo trang/nút'),
('hrm.leave.self', 'Gửi, thu hồi đơn nghỉ phép của mình', 'HRM', 'V202 — phân quyền theo trang/nút'),
('hrm.payroll.calculate', 'Tính, chốt bảng lương', 'HRM', 'V202 — phân quyền theo trang/nút'),
('hrm.payroll.self', 'Xem phiếu lương của mình', 'HRM', 'V202 — phân quyền theo trang/nút'),
('hrm.payroll.view', 'Xem bảng lương toàn hệ thống', 'HRM', 'V202 — phân quyền theo trang/nút'),
('hrm.shift.view', 'Xem ca làm việc', 'HRM', 'V202 — phân quyền theo trang/nút'),
('hrm.work-calendar.view', 'Xem lịch làm việc/nghỉ lễ', 'HRM', 'V202 — phân quyền theo trang/nút'),
('lms.book-catalog.manage', 'Quản lý danh mục sách', 'LMS', 'V202 — phân quyền theo trang/nút'),
('lms.book-catalog.view', 'Xem danh mục sách', 'LMS', 'V202 — phân quyền theo trang/nút'),
('lms.exam.view', 'Xem kho đề', 'LMS', 'V202 — phân quyền theo trang/nút'),
('lms.exercise.deadline.confirm', 'Xác nhận hạn chót nộp muộn', 'LMS', 'V202 — phân quyền theo trang/nút'),
('lms.exercise.report.export', 'Xuất thống kê BTVN', 'LMS', 'V202 — phân quyền theo trang/nút'),
('lms.grading.view', 'Xem hàng chờ chấm bài', 'LMS', 'V202 — phân quyền theo trang/nút'),
('notification.attitude-escalation.approve', 'Duyệt cảnh báo thái độ học tập', 'SYSTEM', 'V202 — phân quyền theo trang/nút'),
('notification.meeting-invite.approve', 'Duyệt thư mời phụ huynh', 'SYSTEM', 'V202 — phân quyền theo trang/nút'),
('student.transfer.create', 'Ghi nhận chuyển lớp/điểm trường', 'STUDENT', 'V202 — phân quyền theo trang/nút'),
('system.ai-usage.view', 'Xem chi phí token AI', 'SYSTEM', 'V202 — phân quyền theo trang/nút'),
('system.settings.view', 'Xem cấu hình hệ thống', 'SYSTEM', 'V202 — phân quyền theo trang/nút'),
('task.overview.team', 'Theo dõi công việc của cấp dưới', 'TASK', 'V202 — phân quyền theo trang/nút'),
('user.status.update', 'Khoá, mở khoá, ngừng hoạt động tài khoản', 'USER', 'V202 — phân quyền theo trang/nút')
ON CONFLICT (code) DO NOTHING;

-- Đặt lại quyền mặc định trên các mã thuộc bảng
DELETE FROM role_permissions rp USING roles r, permissions p
WHERE rp.role_id = r.id AND rp.permission_id = p.id
  AND r.code IN ('TEACHER', 'SITE_MANAGER', 'HEAD_ACADEMIC', 'EXECUTIVE', 'OPS_MANAGER', 'HR_MANAGER', 'ACCOUNTANT', 'CONSULTANT', 'STAFF', 'SYS_ADMIN')
  AND p.code IN (
    'academic.attendance.create',
    'academic.attendance.delete',
    'academic.attendance.mark',
    'academic.attendance.update',
    'academic.attendance.view',
    'academic.class-session.cancel',
    'academic.class-session.checkin',
    'academic.class-session.create',
    'academic.class-session.generate',
    'academic.class-session.import',
    'academic.class-session.reschedule',
    'academic.class.create',
    'academic.class.enrollment.create',
    'academic.class.enrollment.import',
    'academic.class.enrollment.withdraw',
    'academic.class.manage',
    'academic.class.promote',
    'academic.class.teacher.assign',
    'academic.class.update',
    'academic.class.view',
    'academic.class.view-all',
    'academic.comment.approve',
    'academic.comment.manage',
    'academic.comment.view',
    'academic.comment.write',
    'academic.curriculum.approve',
    'academic.curriculum.create',
    'academic.curriculum.customize',
    'academic.curriculum.update',
    'academic.curriculum.view',
    'academic.entrance.score.manage',
    'academic.entrance.setup.create',
    'academic.entrance.setup.delete',
    'academic.entrance.setup.update',
    'academic.entrance.view',
    'academic.grade.approve',
    'academic.grade.book.view',
    'academic.grade.component.create',
    'academic.grade.component.delete',
    'academic.grade.component.update',
    'academic.grade.edit.override',
    'academic.grade.entry',
    'academic.grade.manage',
    'academic.grade.setup.create',
    'academic.grade.setup.delete',
    'academic.grade.setup.update',
    'academic.grade.view',
    'academic.my-timetable.view',
    'academic.skill.create',
    'academic.skill.update',
    'academic.year.manage',
    'crm.lead.assign',
    'crm.lead.convert',
    'crm.lead.create',
    'crm.lead.import',
    'crm.lead.update',
    'crm.lead.view',
    'dashboard.view',
    'facility.equipment.create',
    'facility.equipment.update',
    'facility.feedback.resolve',
    'facility.feedback.view',
    'facility.partner-contract.create',
    'facility.partner-contract.delete',
    'facility.partner-contract.update',
    'facility.partner-contract.view',
    'facility.room.create',
    'facility.room.update',
    'facility.room.view',
    'facility.site-teacher.assign',
    'facility.site-teacher.remove',
    'facility.site.create',
    'facility.site.update',
    'facility.site.view',
    'finance.expense.approve',
    'finance.expense.create',
    'finance.expense.view',
    'finance.invoice.generate',
    'finance.invoice.payment.record',
    'finance.invoice.view',
    'finance.report.view',
    'finance.scholarship.create',
    'finance.scholarship.revoke',
    'finance.tuition-plan.assign',
    'finance.tuition-plan.create',
    'finance.tuition-plan.update',
    'finance.tuition-plan.view',
    'hrm.attendance-site.manage',
    'hrm.attendance-site.view',
    'hrm.attendance.self',
    'hrm.attendance.view-all',
    'hrm.department.create',
    'hrm.department.delete',
    'hrm.department.update',
    'hrm.department.view',
    'hrm.employee-schedule.view',
    'hrm.employee-shift.assign',
    'hrm.employee.create',
    'hrm.employee.import',
    'hrm.employee.update',
    'hrm.employee.view',
    'hrm.leave.approve',
    'hrm.leave.self',
    'hrm.payroll.calculate',
    'hrm.payroll.self',
    'hrm.payroll.view',
    'hrm.position.create',
    'hrm.position.delete',
    'hrm.position.update',
    'hrm.position.view',
    'hrm.shift.create',
    'hrm.shift.update',
    'hrm.shift.view',
    'hrm.work-calendar.create',
    'hrm.work-calendar.delete',
    'hrm.work-calendar.view',
    'lms.book-catalog.manage',
    'lms.book-catalog.view',
    'lms.document.create',
    'lms.document.update',
    'lms.document.view',
    'lms.exam-question.create',
    'lms.exam-question.update',
    'lms.exam-question.view',
    'lms.exam.assign',
    'lms.exam.create',
    'lms.exam.delete',
    'lms.exam.manage',
    'lms.exam.update',
    'lms.exam.view',
    'lms.exercise-report.manage',
    'lms.exercise.create',
    'lms.exercise.deadline.confirm',
    'lms.exercise.publish',
    'lms.exercise.report.export',
    'lms.exercise.report.view',
    'lms.exercise.update',
    'lms.grading.manage',
    'lms.grading.view',
    'lms.review-video.assign',
    'lms.review-video.create',
    'lms.review-video.delete',
    'lms.review-video.manage',
    'lms.review-video.update',
    'lms.review-video.view',
    'notification.attitude-escalation.approve',
    'notification.meeting-invite.approve',
    'notification.send.manual',
    'permission.audit.view',
    'permission.override.delete',
    'permission.override.set',
    'permission.override.view',
    'permission.role.create',
    'permission.role.delete',
    'permission.role.update',
    'permission.role.view',
    'report.actual-periods.view',
    'report.daily-comment.view',
    'report.enrollment-stats.view',
    'report.generate',
    'report.grade.view',
    'report.student-progress.view',
    'report.template.create',
    'report.template.delete',
    'report.template.update',
    'report.template.view',
    'student.parent.create',
    'student.parent.import',
    'student.parent.link.create',
    'student.parent.link.delete',
    'student.parent.update',
    'student.parent.view',
    'student.profile.create',
    'student.profile.import',
    'student.profile.update',
    'student.profile.view',
    'student.status.manage',
    'student.transfer.create',
    'system.ai-usage.view',
    'system.settings.manage',
    'system.settings.view',
    'task.assign',
    'task.manage',
    'task.overview.company',
    'task.overview.team',
    'task.receive',
    'user.create',
    'user.role.assign',
    'user.role.revoke',
    'user.role.view',
    'user.status.update',
    'user.update',
    'user.view');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM (VALUES
  ('TEACHER', 'academic.attendance.mark'),
  ('TEACHER', 'academic.attendance.view'),
  ('TEACHER', 'academic.class-session.checkin'),
  ('TEACHER', 'academic.class.view'),
  ('TEACHER', 'academic.comment.view'),
  ('TEACHER', 'academic.comment.write'),
  ('TEACHER', 'academic.grade.entry'),
  ('TEACHER', 'academic.grade.view'),
  ('TEACHER', 'academic.my-timetable.view'),
  ('TEACHER', 'dashboard.view'),
  ('TEACHER', 'hrm.attendance.self'),
  ('TEACHER', 'hrm.leave.self'),
  ('TEACHER', 'hrm.payroll.self'),
  ('TEACHER', 'lms.document.create'),
  ('TEACHER', 'lms.document.update'),
  ('TEACHER', 'lms.document.view'),
  ('TEACHER', 'lms.exam-question.create'),
  ('TEACHER', 'lms.exam-question.update'),
  ('TEACHER', 'lms.exam-question.view'),
  ('TEACHER', 'lms.exam.assign'),
  ('TEACHER', 'lms.exam.create'),
  ('TEACHER', 'lms.exam.delete'),
  ('TEACHER', 'lms.exam.update'),
  ('TEACHER', 'lms.exam.view'),
  ('TEACHER', 'lms.exercise.create'),
  ('TEACHER', 'lms.exercise.deadline.confirm'),
  ('TEACHER', 'lms.exercise.publish'),
  ('TEACHER', 'lms.exercise.report.export'),
  ('TEACHER', 'lms.exercise.report.view'),
  ('TEACHER', 'lms.exercise.update'),
  ('TEACHER', 'lms.grading.manage'),
  ('TEACHER', 'lms.grading.view'),
  ('TEACHER', 'lms.review-video.assign'),
  ('TEACHER', 'lms.review-video.create'),
  ('TEACHER', 'lms.review-video.delete'),
  ('TEACHER', 'lms.review-video.update'),
  ('TEACHER', 'lms.review-video.view'),
  ('SITE_MANAGER', 'academic.attendance.create'),
  ('SITE_MANAGER', 'academic.attendance.delete'),
  ('SITE_MANAGER', 'academic.attendance.update'),
  ('SITE_MANAGER', 'academic.attendance.view'),
  ('SITE_MANAGER', 'academic.class.view'),
  ('SITE_MANAGER', 'academic.comment.approve'),
  ('SITE_MANAGER', 'academic.comment.view'),
  ('SITE_MANAGER', 'academic.grade.approve'),
  ('SITE_MANAGER', 'academic.grade.book.view'),
  ('SITE_MANAGER', 'academic.grade.edit.override'),
  ('SITE_MANAGER', 'academic.grade.view'),
  ('SITE_MANAGER', 'dashboard.view'),
  ('SITE_MANAGER', 'facility.feedback.resolve'),
  ('SITE_MANAGER', 'facility.feedback.view'),
  ('SITE_MANAGER', 'hrm.attendance.self'),
  ('SITE_MANAGER', 'hrm.attendance.view-all'),
  ('SITE_MANAGER', 'hrm.leave.approve'),
  ('SITE_MANAGER', 'hrm.leave.self'),
  ('SITE_MANAGER', 'hrm.payroll.self'),
  ('SITE_MANAGER', 'lms.exercise.report.export'),
  ('SITE_MANAGER', 'lms.exercise.report.view'),
  ('SITE_MANAGER', 'notification.attitude-escalation.approve'),
  ('SITE_MANAGER', 'notification.meeting-invite.approve'),
  ('SITE_MANAGER', 'report.actual-periods.view'),
  ('SITE_MANAGER', 'report.daily-comment.view'),
  ('SITE_MANAGER', 'report.enrollment-stats.view'),
  ('SITE_MANAGER', 'report.generate'),
  ('SITE_MANAGER', 'report.grade.view'),
  ('SITE_MANAGER', 'report.student-progress.view'),
  ('SITE_MANAGER', 'report.template.create'),
  ('SITE_MANAGER', 'report.template.delete'),
  ('SITE_MANAGER', 'report.template.update'),
  ('SITE_MANAGER', 'report.template.view'),
  ('SITE_MANAGER', 'student.parent.create'),
  ('SITE_MANAGER', 'student.parent.import'),
  ('SITE_MANAGER', 'student.parent.link.create'),
  ('SITE_MANAGER', 'student.parent.link.delete'),
  ('SITE_MANAGER', 'student.parent.update'),
  ('SITE_MANAGER', 'student.parent.view'),
  ('SITE_MANAGER', 'student.profile.create'),
  ('SITE_MANAGER', 'student.profile.import'),
  ('SITE_MANAGER', 'student.profile.update'),
  ('SITE_MANAGER', 'student.profile.view'),
  ('SITE_MANAGER', 'student.status.manage'),
  ('SITE_MANAGER', 'student.transfer.create'),
  ('HEAD_ACADEMIC', 'academic.attendance.create'),
  ('HEAD_ACADEMIC', 'academic.attendance.delete'),
  ('HEAD_ACADEMIC', 'academic.attendance.mark'),
  ('HEAD_ACADEMIC', 'academic.attendance.update'),
  ('HEAD_ACADEMIC', 'academic.attendance.view'),
  ('HEAD_ACADEMIC', 'academic.class-session.cancel'),
  ('HEAD_ACADEMIC', 'academic.class-session.create'),
  ('HEAD_ACADEMIC', 'academic.class-session.generate'),
  ('HEAD_ACADEMIC', 'academic.class-session.import'),
  ('HEAD_ACADEMIC', 'academic.class-session.reschedule'),
  ('HEAD_ACADEMIC', 'academic.class.create'),
  ('HEAD_ACADEMIC', 'academic.class.enrollment.create'),
  ('HEAD_ACADEMIC', 'academic.class.enrollment.import'),
  ('HEAD_ACADEMIC', 'academic.class.enrollment.withdraw'),
  ('HEAD_ACADEMIC', 'academic.class.promote'),
  ('HEAD_ACADEMIC', 'academic.class.teacher.assign'),
  ('HEAD_ACADEMIC', 'academic.class.update'),
  ('HEAD_ACADEMIC', 'academic.class.view'),
  ('HEAD_ACADEMIC', 'academic.class.view-all'),
  ('HEAD_ACADEMIC', 'academic.comment.approve'),
  ('HEAD_ACADEMIC', 'academic.comment.manage'),
  ('HEAD_ACADEMIC', 'academic.comment.view'),
  ('HEAD_ACADEMIC', 'academic.curriculum.approve'),
  ('HEAD_ACADEMIC', 'academic.curriculum.create'),
  ('HEAD_ACADEMIC', 'academic.curriculum.customize'),
  ('HEAD_ACADEMIC', 'academic.curriculum.update'),
  ('HEAD_ACADEMIC', 'academic.curriculum.view'),
  ('HEAD_ACADEMIC', 'academic.entrance.score.manage'),
  ('HEAD_ACADEMIC', 'academic.entrance.setup.create'),
  ('HEAD_ACADEMIC', 'academic.entrance.setup.delete'),
  ('HEAD_ACADEMIC', 'academic.entrance.setup.update'),
  ('HEAD_ACADEMIC', 'academic.entrance.view'),
  ('HEAD_ACADEMIC', 'academic.grade.approve'),
  ('HEAD_ACADEMIC', 'academic.grade.book.view'),
  ('HEAD_ACADEMIC', 'academic.grade.component.create'),
  ('HEAD_ACADEMIC', 'academic.grade.component.delete'),
  ('HEAD_ACADEMIC', 'academic.grade.component.update'),
  ('HEAD_ACADEMIC', 'academic.grade.edit.override'),
  ('HEAD_ACADEMIC', 'academic.grade.manage'),
  ('HEAD_ACADEMIC', 'academic.grade.setup.create'),
  ('HEAD_ACADEMIC', 'academic.grade.setup.delete'),
  ('HEAD_ACADEMIC', 'academic.grade.setup.update'),
  ('HEAD_ACADEMIC', 'academic.grade.view'),
  ('HEAD_ACADEMIC', 'academic.skill.create'),
  ('HEAD_ACADEMIC', 'academic.skill.update'),
  ('HEAD_ACADEMIC', 'dashboard.view'),
  ('HEAD_ACADEMIC', 'hrm.attendance.self'),
  ('HEAD_ACADEMIC', 'hrm.attendance.view-all'),
  ('HEAD_ACADEMIC', 'hrm.employee-schedule.view'),
  ('HEAD_ACADEMIC', 'hrm.leave.approve'),
  ('HEAD_ACADEMIC', 'hrm.leave.self'),
  ('HEAD_ACADEMIC', 'hrm.payroll.self'),
  ('HEAD_ACADEMIC', 'lms.document.create'),
  ('HEAD_ACADEMIC', 'lms.document.update'),
  ('HEAD_ACADEMIC', 'lms.document.view'),
  ('HEAD_ACADEMIC', 'lms.exam-question.create'),
  ('HEAD_ACADEMIC', 'lms.exam-question.update'),
  ('HEAD_ACADEMIC', 'lms.exam-question.view'),
  ('HEAD_ACADEMIC', 'lms.exam.manage'),
  ('HEAD_ACADEMIC', 'lms.exam.view'),
  ('HEAD_ACADEMIC', 'lms.exercise-report.manage'),
  ('HEAD_ACADEMIC', 'lms.exercise.deadline.confirm'),
  ('HEAD_ACADEMIC', 'lms.exercise.report.export'),
  ('HEAD_ACADEMIC', 'lms.exercise.report.view'),
  ('HEAD_ACADEMIC', 'lms.review-video.manage'),
  ('HEAD_ACADEMIC', 'lms.review-video.view'),
  ('HEAD_ACADEMIC', 'report.actual-periods.view'),
  ('HEAD_ACADEMIC', 'report.daily-comment.view'),
  ('HEAD_ACADEMIC', 'report.enrollment-stats.view'),
  ('HEAD_ACADEMIC', 'report.generate'),
  ('HEAD_ACADEMIC', 'report.grade.view'),
  ('HEAD_ACADEMIC', 'report.student-progress.view'),
  ('HEAD_ACADEMIC', 'report.template.create'),
  ('HEAD_ACADEMIC', 'report.template.delete'),
  ('HEAD_ACADEMIC', 'report.template.update'),
  ('HEAD_ACADEMIC', 'report.template.view'),
  ('HEAD_ACADEMIC', 'student.profile.view'),
  ('HEAD_ACADEMIC', 'student.status.manage'),
  ('HEAD_ACADEMIC', 'student.transfer.create'),
  ('HEAD_ACADEMIC', 'task.assign'),
  ('HEAD_ACADEMIC', 'task.overview.team'),
  ('HEAD_ACADEMIC', 'task.receive'),
  ('EXECUTIVE', 'academic.attendance.create'),
  ('EXECUTIVE', 'academic.attendance.delete'),
  ('EXECUTIVE', 'academic.attendance.mark'),
  ('EXECUTIVE', 'academic.attendance.update'),
  ('EXECUTIVE', 'academic.attendance.view'),
  ('EXECUTIVE', 'academic.class-session.cancel'),
  ('EXECUTIVE', 'academic.class-session.checkin'),
  ('EXECUTIVE', 'academic.class-session.create'),
  ('EXECUTIVE', 'academic.class-session.generate'),
  ('EXECUTIVE', 'academic.class-session.import'),
  ('EXECUTIVE', 'academic.class-session.reschedule'),
  ('EXECUTIVE', 'academic.class.create'),
  ('EXECUTIVE', 'academic.class.enrollment.create'),
  ('EXECUTIVE', 'academic.class.enrollment.import'),
  ('EXECUTIVE', 'academic.class.enrollment.withdraw'),
  ('EXECUTIVE', 'academic.class.promote'),
  ('EXECUTIVE', 'academic.class.teacher.assign'),
  ('EXECUTIVE', 'academic.class.update'),
  ('EXECUTIVE', 'academic.class.view'),
  ('EXECUTIVE', 'academic.class.view-all'),
  ('EXECUTIVE', 'academic.comment.approve'),
  ('EXECUTIVE', 'academic.comment.manage'),
  ('EXECUTIVE', 'academic.comment.view'),
  ('EXECUTIVE', 'academic.comment.write'),
  ('EXECUTIVE', 'academic.curriculum.approve'),
  ('EXECUTIVE', 'academic.curriculum.create'),
  ('EXECUTIVE', 'academic.curriculum.customize'),
  ('EXECUTIVE', 'academic.curriculum.update'),
  ('EXECUTIVE', 'academic.curriculum.view'),
  ('EXECUTIVE', 'academic.entrance.score.manage'),
  ('EXECUTIVE', 'academic.entrance.setup.create'),
  ('EXECUTIVE', 'academic.entrance.setup.delete'),
  ('EXECUTIVE', 'academic.entrance.setup.update'),
  ('EXECUTIVE', 'academic.entrance.view'),
  ('EXECUTIVE', 'academic.grade.approve'),
  ('EXECUTIVE', 'academic.grade.book.view'),
  ('EXECUTIVE', 'academic.grade.component.create'),
  ('EXECUTIVE', 'academic.grade.component.delete'),
  ('EXECUTIVE', 'academic.grade.component.update'),
  ('EXECUTIVE', 'academic.grade.edit.override'),
  ('EXECUTIVE', 'academic.grade.entry'),
  ('EXECUTIVE', 'academic.grade.manage'),
  ('EXECUTIVE', 'academic.grade.setup.create'),
  ('EXECUTIVE', 'academic.grade.setup.delete'),
  ('EXECUTIVE', 'academic.grade.setup.update'),
  ('EXECUTIVE', 'academic.grade.view'),
  ('EXECUTIVE', 'academic.my-timetable.view'),
  ('EXECUTIVE', 'academic.skill.create'),
  ('EXECUTIVE', 'academic.skill.update'),
  ('EXECUTIVE', 'academic.year.manage'),
  ('EXECUTIVE', 'crm.lead.assign'),
  ('EXECUTIVE', 'crm.lead.convert'),
  ('EXECUTIVE', 'crm.lead.create'),
  ('EXECUTIVE', 'crm.lead.import'),
  ('EXECUTIVE', 'crm.lead.update'),
  ('EXECUTIVE', 'crm.lead.view'),
  ('EXECUTIVE', 'dashboard.view'),
  ('EXECUTIVE', 'facility.equipment.create'),
  ('EXECUTIVE', 'facility.equipment.update'),
  ('EXECUTIVE', 'facility.feedback.resolve'),
  ('EXECUTIVE', 'facility.feedback.view'),
  ('EXECUTIVE', 'facility.partner-contract.create'),
  ('EXECUTIVE', 'facility.partner-contract.delete'),
  ('EXECUTIVE', 'facility.partner-contract.update'),
  ('EXECUTIVE', 'facility.partner-contract.view'),
  ('EXECUTIVE', 'facility.room.create'),
  ('EXECUTIVE', 'facility.room.update'),
  ('EXECUTIVE', 'facility.room.view'),
  ('EXECUTIVE', 'facility.site-teacher.assign'),
  ('EXECUTIVE', 'facility.site-teacher.remove'),
  ('EXECUTIVE', 'facility.site.create'),
  ('EXECUTIVE', 'facility.site.update'),
  ('EXECUTIVE', 'facility.site.view'),
  ('EXECUTIVE', 'finance.expense.approve'),
  ('EXECUTIVE', 'finance.expense.create'),
  ('EXECUTIVE', 'finance.expense.view'),
  ('EXECUTIVE', 'finance.invoice.generate'),
  ('EXECUTIVE', 'finance.invoice.payment.record'),
  ('EXECUTIVE', 'finance.invoice.view'),
  ('EXECUTIVE', 'finance.report.view'),
  ('EXECUTIVE', 'finance.scholarship.create'),
  ('EXECUTIVE', 'finance.scholarship.revoke'),
  ('EXECUTIVE', 'finance.tuition-plan.assign'),
  ('EXECUTIVE', 'finance.tuition-plan.create'),
  ('EXECUTIVE', 'finance.tuition-plan.update'),
  ('EXECUTIVE', 'finance.tuition-plan.view'),
  ('EXECUTIVE', 'hrm.attendance-site.manage'),
  ('EXECUTIVE', 'hrm.attendance-site.view'),
  ('EXECUTIVE', 'hrm.attendance.self'),
  ('EXECUTIVE', 'hrm.attendance.view-all'),
  ('EXECUTIVE', 'hrm.department.create'),
  ('EXECUTIVE', 'hrm.department.delete'),
  ('EXECUTIVE', 'hrm.department.update'),
  ('EXECUTIVE', 'hrm.department.view'),
  ('EXECUTIVE', 'hrm.employee-schedule.view'),
  ('EXECUTIVE', 'hrm.employee-shift.assign'),
  ('EXECUTIVE', 'hrm.employee.create'),
  ('EXECUTIVE', 'hrm.employee.import'),
  ('EXECUTIVE', 'hrm.employee.update'),
  ('EXECUTIVE', 'hrm.employee.view'),
  ('EXECUTIVE', 'hrm.leave.approve'),
  ('EXECUTIVE', 'hrm.leave.self'),
  ('EXECUTIVE', 'hrm.payroll.calculate'),
  ('EXECUTIVE', 'hrm.payroll.self'),
  ('EXECUTIVE', 'hrm.payroll.view'),
  ('EXECUTIVE', 'hrm.position.create'),
  ('EXECUTIVE', 'hrm.position.delete'),
  ('EXECUTIVE', 'hrm.position.update'),
  ('EXECUTIVE', 'hrm.position.view'),
  ('EXECUTIVE', 'hrm.shift.create'),
  ('EXECUTIVE', 'hrm.shift.update'),
  ('EXECUTIVE', 'hrm.shift.view'),
  ('EXECUTIVE', 'hrm.work-calendar.create'),
  ('EXECUTIVE', 'hrm.work-calendar.delete'),
  ('EXECUTIVE', 'hrm.work-calendar.view'),
  ('EXECUTIVE', 'lms.book-catalog.manage'),
  ('EXECUTIVE', 'lms.book-catalog.view'),
  ('EXECUTIVE', 'lms.document.create'),
  ('EXECUTIVE', 'lms.document.update'),
  ('EXECUTIVE', 'lms.document.view'),
  ('EXECUTIVE', 'lms.exam-question.create'),
  ('EXECUTIVE', 'lms.exam-question.update'),
  ('EXECUTIVE', 'lms.exam-question.view'),
  ('EXECUTIVE', 'lms.exam.assign'),
  ('EXECUTIVE', 'lms.exam.create'),
  ('EXECUTIVE', 'lms.exam.delete'),
  ('EXECUTIVE', 'lms.exam.manage'),
  ('EXECUTIVE', 'lms.exam.update'),
  ('EXECUTIVE', 'lms.exam.view'),
  ('EXECUTIVE', 'lms.exercise-report.manage'),
  ('EXECUTIVE', 'lms.exercise.create'),
  ('EXECUTIVE', 'lms.exercise.deadline.confirm'),
  ('EXECUTIVE', 'lms.exercise.publish'),
  ('EXECUTIVE', 'lms.exercise.report.export'),
  ('EXECUTIVE', 'lms.exercise.report.view'),
  ('EXECUTIVE', 'lms.exercise.update'),
  ('EXECUTIVE', 'lms.grading.manage'),
  ('EXECUTIVE', 'lms.grading.view'),
  ('EXECUTIVE', 'lms.review-video.assign'),
  ('EXECUTIVE', 'lms.review-video.create'),
  ('EXECUTIVE', 'lms.review-video.delete'),
  ('EXECUTIVE', 'lms.review-video.manage'),
  ('EXECUTIVE', 'lms.review-video.update'),
  ('EXECUTIVE', 'lms.review-video.view'),
  ('EXECUTIVE', 'notification.attitude-escalation.approve'),
  ('EXECUTIVE', 'notification.meeting-invite.approve'),
  ('EXECUTIVE', 'notification.send.manual'),
  ('EXECUTIVE', 'permission.audit.view'),
  ('EXECUTIVE', 'permission.override.delete'),
  ('EXECUTIVE', 'permission.override.set'),
  ('EXECUTIVE', 'permission.override.view'),
  ('EXECUTIVE', 'permission.role.create'),
  ('EXECUTIVE', 'permission.role.delete'),
  ('EXECUTIVE', 'permission.role.update'),
  ('EXECUTIVE', 'permission.role.view'),
  ('EXECUTIVE', 'report.actual-periods.view'),
  ('EXECUTIVE', 'report.daily-comment.view'),
  ('EXECUTIVE', 'report.enrollment-stats.view'),
  ('EXECUTIVE', 'report.generate'),
  ('EXECUTIVE', 'report.grade.view'),
  ('EXECUTIVE', 'report.student-progress.view'),
  ('EXECUTIVE', 'report.template.create'),
  ('EXECUTIVE', 'report.template.delete'),
  ('EXECUTIVE', 'report.template.update'),
  ('EXECUTIVE', 'report.template.view'),
  ('EXECUTIVE', 'student.parent.create'),
  ('EXECUTIVE', 'student.parent.import'),
  ('EXECUTIVE', 'student.parent.link.create'),
  ('EXECUTIVE', 'student.parent.link.delete'),
  ('EXECUTIVE', 'student.parent.update'),
  ('EXECUTIVE', 'student.parent.view'),
  ('EXECUTIVE', 'student.profile.create'),
  ('EXECUTIVE', 'student.profile.import'),
  ('EXECUTIVE', 'student.profile.update'),
  ('EXECUTIVE', 'student.profile.view'),
  ('EXECUTIVE', 'student.status.manage'),
  ('EXECUTIVE', 'student.transfer.create'),
  ('EXECUTIVE', 'system.ai-usage.view'),
  ('EXECUTIVE', 'system.settings.manage'),
  ('EXECUTIVE', 'system.settings.view'),
  ('EXECUTIVE', 'task.assign'),
  ('EXECUTIVE', 'task.manage'),
  ('EXECUTIVE', 'task.overview.company'),
  ('EXECUTIVE', 'task.overview.team'),
  ('EXECUTIVE', 'task.receive'),
  ('EXECUTIVE', 'user.create'),
  ('EXECUTIVE', 'user.role.assign'),
  ('EXECUTIVE', 'user.role.revoke'),
  ('EXECUTIVE', 'user.role.view'),
  ('EXECUTIVE', 'user.status.update'),
  ('EXECUTIVE', 'user.update'),
  ('EXECUTIVE', 'user.view'),
  ('OPS_MANAGER', 'academic.class.view'),
  ('OPS_MANAGER', 'academic.class.view-all'),
  ('OPS_MANAGER', 'academic.year.manage'),
  ('OPS_MANAGER', 'crm.lead.assign'),
  ('OPS_MANAGER', 'crm.lead.view'),
  ('OPS_MANAGER', 'dashboard.view'),
  ('OPS_MANAGER', 'facility.equipment.create'),
  ('OPS_MANAGER', 'facility.equipment.update'),
  ('OPS_MANAGER', 'facility.partner-contract.create'),
  ('OPS_MANAGER', 'facility.partner-contract.delete'),
  ('OPS_MANAGER', 'facility.partner-contract.update'),
  ('OPS_MANAGER', 'facility.partner-contract.view'),
  ('OPS_MANAGER', 'facility.room.create'),
  ('OPS_MANAGER', 'facility.room.update'),
  ('OPS_MANAGER', 'facility.room.view'),
  ('OPS_MANAGER', 'facility.site-teacher.assign'),
  ('OPS_MANAGER', 'facility.site-teacher.remove'),
  ('OPS_MANAGER', 'facility.site.create'),
  ('OPS_MANAGER', 'facility.site.update'),
  ('OPS_MANAGER', 'facility.site.view'),
  ('OPS_MANAGER', 'hrm.attendance-site.manage'),
  ('OPS_MANAGER', 'hrm.attendance-site.view'),
  ('OPS_MANAGER', 'hrm.attendance.self'),
  ('OPS_MANAGER', 'hrm.attendance.view-all'),
  ('OPS_MANAGER', 'hrm.employee-schedule.view'),
  ('OPS_MANAGER', 'hrm.leave.approve'),
  ('OPS_MANAGER', 'hrm.leave.self'),
  ('OPS_MANAGER', 'hrm.payroll.self'),
  ('OPS_MANAGER', 'report.actual-periods.view'),
  ('OPS_MANAGER', 'report.daily-comment.view'),
  ('OPS_MANAGER', 'report.enrollment-stats.view'),
  ('OPS_MANAGER', 'report.grade.view'),
  ('OPS_MANAGER', 'report.student-progress.view'),
  ('OPS_MANAGER', 'student.profile.view'),
  ('HR_MANAGER', 'dashboard.view'),
  ('HR_MANAGER', 'hrm.attendance.self'),
  ('HR_MANAGER', 'hrm.attendance.view-all'),
  ('HR_MANAGER', 'hrm.department.create'),
  ('HR_MANAGER', 'hrm.department.delete'),
  ('HR_MANAGER', 'hrm.department.update'),
  ('HR_MANAGER', 'hrm.department.view'),
  ('HR_MANAGER', 'hrm.employee-schedule.view'),
  ('HR_MANAGER', 'hrm.employee-shift.assign'),
  ('HR_MANAGER', 'hrm.employee.create'),
  ('HR_MANAGER', 'hrm.employee.import'),
  ('HR_MANAGER', 'hrm.employee.update'),
  ('HR_MANAGER', 'hrm.employee.view'),
  ('HR_MANAGER', 'hrm.leave.approve'),
  ('HR_MANAGER', 'hrm.leave.self'),
  ('HR_MANAGER', 'hrm.payroll.calculate'),
  ('HR_MANAGER', 'hrm.payroll.self'),
  ('HR_MANAGER', 'hrm.payroll.view'),
  ('HR_MANAGER', 'hrm.position.create'),
  ('HR_MANAGER', 'hrm.position.delete'),
  ('HR_MANAGER', 'hrm.position.update'),
  ('HR_MANAGER', 'hrm.position.view'),
  ('HR_MANAGER', 'hrm.shift.create'),
  ('HR_MANAGER', 'hrm.shift.update'),
  ('HR_MANAGER', 'hrm.shift.view'),
  ('HR_MANAGER', 'hrm.work-calendar.create'),
  ('HR_MANAGER', 'hrm.work-calendar.delete'),
  ('HR_MANAGER', 'hrm.work-calendar.view'),
  ('ACCOUNTANT', 'academic.class.view'),
  ('ACCOUNTANT', 'dashboard.view'),
  ('ACCOUNTANT', 'finance.expense.create'),
  ('ACCOUNTANT', 'finance.expense.view'),
  ('ACCOUNTANT', 'finance.invoice.generate'),
  ('ACCOUNTANT', 'finance.invoice.payment.record'),
  ('ACCOUNTANT', 'finance.invoice.view'),
  ('ACCOUNTANT', 'finance.report.view'),
  ('ACCOUNTANT', 'finance.scholarship.create'),
  ('ACCOUNTANT', 'finance.scholarship.revoke'),
  ('ACCOUNTANT', 'finance.tuition-plan.assign'),
  ('ACCOUNTANT', 'finance.tuition-plan.create'),
  ('ACCOUNTANT', 'finance.tuition-plan.update'),
  ('ACCOUNTANT', 'finance.tuition-plan.view'),
  ('ACCOUNTANT', 'hrm.attendance.self'),
  ('ACCOUNTANT', 'hrm.leave.self'),
  ('ACCOUNTANT', 'hrm.payroll.self'),
  ('ACCOUNTANT', 'hrm.payroll.view'),
  ('ACCOUNTANT', 'report.enrollment-stats.view'),
  ('ACCOUNTANT', 'student.parent.view'),
  ('ACCOUNTANT', 'student.profile.view'),
  ('CONSULTANT', 'academic.class.view'),
  ('CONSULTANT', 'academic.entrance.view'),
  ('CONSULTANT', 'crm.lead.convert'),
  ('CONSULTANT', 'crm.lead.create'),
  ('CONSULTANT', 'crm.lead.import'),
  ('CONSULTANT', 'crm.lead.update'),
  ('CONSULTANT', 'crm.lead.view'),
  ('CONSULTANT', 'dashboard.view'),
  ('CONSULTANT', 'hrm.attendance.self'),
  ('CONSULTANT', 'hrm.leave.self'),
  ('CONSULTANT', 'hrm.payroll.self'),
  ('CONSULTANT', 'student.parent.view'),
  ('CONSULTANT', 'student.profile.view'),
  ('STAFF', 'academic.class.view'),
  ('STAFF', 'dashboard.view'),
  ('STAFF', 'facility.equipment.create'),
  ('STAFF', 'facility.equipment.update'),
  ('STAFF', 'facility.room.create'),
  ('STAFF', 'facility.room.update'),
  ('STAFF', 'facility.room.view'),
  ('STAFF', 'finance.expense.create'),
  ('STAFF', 'finance.expense.view'),
  ('STAFF', 'hrm.attendance.self'),
  ('STAFF', 'hrm.leave.self'),
  ('STAFF', 'hrm.payroll.self'),
  ('STAFF', 'student.parent.create'),
  ('STAFF', 'student.parent.import'),
  ('STAFF', 'student.parent.link.create'),
  ('STAFF', 'student.parent.link.delete'),
  ('STAFF', 'student.parent.update'),
  ('STAFF', 'student.parent.view'),
  ('STAFF', 'student.profile.create'),
  ('STAFF', 'student.profile.import'),
  ('STAFF', 'student.profile.update'),
  ('STAFF', 'student.profile.view'),
  ('STAFF', 'student.status.manage'),
  ('STAFF', 'student.transfer.create'),
  ('SYS_ADMIN', 'academic.attendance.create'),
  ('SYS_ADMIN', 'academic.attendance.delete'),
  ('SYS_ADMIN', 'academic.attendance.mark'),
  ('SYS_ADMIN', 'academic.attendance.update'),
  ('SYS_ADMIN', 'academic.attendance.view'),
  ('SYS_ADMIN', 'academic.class-session.cancel'),
  ('SYS_ADMIN', 'academic.class-session.checkin'),
  ('SYS_ADMIN', 'academic.class-session.create'),
  ('SYS_ADMIN', 'academic.class-session.generate'),
  ('SYS_ADMIN', 'academic.class-session.import'),
  ('SYS_ADMIN', 'academic.class-session.reschedule'),
  ('SYS_ADMIN', 'academic.class.create'),
  ('SYS_ADMIN', 'academic.class.enrollment.create'),
  ('SYS_ADMIN', 'academic.class.enrollment.import'),
  ('SYS_ADMIN', 'academic.class.enrollment.withdraw'),
  ('SYS_ADMIN', 'academic.class.promote'),
  ('SYS_ADMIN', 'academic.class.teacher.assign'),
  ('SYS_ADMIN', 'academic.class.update'),
  ('SYS_ADMIN', 'academic.class.view'),
  ('SYS_ADMIN', 'academic.class.view-all'),
  ('SYS_ADMIN', 'academic.comment.approve'),
  ('SYS_ADMIN', 'academic.comment.manage'),
  ('SYS_ADMIN', 'academic.comment.view'),
  ('SYS_ADMIN', 'academic.comment.write'),
  ('SYS_ADMIN', 'academic.curriculum.approve'),
  ('SYS_ADMIN', 'academic.curriculum.create'),
  ('SYS_ADMIN', 'academic.curriculum.customize'),
  ('SYS_ADMIN', 'academic.curriculum.update'),
  ('SYS_ADMIN', 'academic.curriculum.view'),
  ('SYS_ADMIN', 'academic.entrance.score.manage'),
  ('SYS_ADMIN', 'academic.entrance.setup.create'),
  ('SYS_ADMIN', 'academic.entrance.setup.delete'),
  ('SYS_ADMIN', 'academic.entrance.setup.update'),
  ('SYS_ADMIN', 'academic.entrance.view'),
  ('SYS_ADMIN', 'academic.grade.approve'),
  ('SYS_ADMIN', 'academic.grade.book.view'),
  ('SYS_ADMIN', 'academic.grade.component.create'),
  ('SYS_ADMIN', 'academic.grade.component.delete'),
  ('SYS_ADMIN', 'academic.grade.component.update'),
  ('SYS_ADMIN', 'academic.grade.edit.override'),
  ('SYS_ADMIN', 'academic.grade.entry'),
  ('SYS_ADMIN', 'academic.grade.manage'),
  ('SYS_ADMIN', 'academic.grade.setup.create'),
  ('SYS_ADMIN', 'academic.grade.setup.delete'),
  ('SYS_ADMIN', 'academic.grade.setup.update'),
  ('SYS_ADMIN', 'academic.grade.view'),
  ('SYS_ADMIN', 'academic.my-timetable.view'),
  ('SYS_ADMIN', 'academic.skill.create'),
  ('SYS_ADMIN', 'academic.skill.update'),
  ('SYS_ADMIN', 'academic.year.manage'),
  ('SYS_ADMIN', 'crm.lead.assign'),
  ('SYS_ADMIN', 'crm.lead.convert'),
  ('SYS_ADMIN', 'crm.lead.create'),
  ('SYS_ADMIN', 'crm.lead.import'),
  ('SYS_ADMIN', 'crm.lead.update'),
  ('SYS_ADMIN', 'crm.lead.view'),
  ('SYS_ADMIN', 'dashboard.view'),
  ('SYS_ADMIN', 'facility.equipment.create'),
  ('SYS_ADMIN', 'facility.equipment.update'),
  ('SYS_ADMIN', 'facility.feedback.resolve'),
  ('SYS_ADMIN', 'facility.feedback.view'),
  ('SYS_ADMIN', 'facility.partner-contract.create'),
  ('SYS_ADMIN', 'facility.partner-contract.delete'),
  ('SYS_ADMIN', 'facility.partner-contract.update'),
  ('SYS_ADMIN', 'facility.partner-contract.view'),
  ('SYS_ADMIN', 'facility.room.create'),
  ('SYS_ADMIN', 'facility.room.update'),
  ('SYS_ADMIN', 'facility.room.view'),
  ('SYS_ADMIN', 'facility.site-teacher.assign'),
  ('SYS_ADMIN', 'facility.site-teacher.remove'),
  ('SYS_ADMIN', 'facility.site.create'),
  ('SYS_ADMIN', 'facility.site.update'),
  ('SYS_ADMIN', 'facility.site.view'),
  ('SYS_ADMIN', 'finance.expense.approve'),
  ('SYS_ADMIN', 'finance.expense.create'),
  ('SYS_ADMIN', 'finance.expense.view'),
  ('SYS_ADMIN', 'finance.invoice.generate'),
  ('SYS_ADMIN', 'finance.invoice.payment.record'),
  ('SYS_ADMIN', 'finance.invoice.view'),
  ('SYS_ADMIN', 'finance.report.view'),
  ('SYS_ADMIN', 'finance.scholarship.create'),
  ('SYS_ADMIN', 'finance.scholarship.revoke'),
  ('SYS_ADMIN', 'finance.tuition-plan.assign'),
  ('SYS_ADMIN', 'finance.tuition-plan.create'),
  ('SYS_ADMIN', 'finance.tuition-plan.update'),
  ('SYS_ADMIN', 'finance.tuition-plan.view'),
  ('SYS_ADMIN', 'hrm.attendance-site.manage'),
  ('SYS_ADMIN', 'hrm.attendance-site.view'),
  ('SYS_ADMIN', 'hrm.attendance.self'),
  ('SYS_ADMIN', 'hrm.attendance.view-all'),
  ('SYS_ADMIN', 'hrm.department.create'),
  ('SYS_ADMIN', 'hrm.department.delete'),
  ('SYS_ADMIN', 'hrm.department.update'),
  ('SYS_ADMIN', 'hrm.department.view'),
  ('SYS_ADMIN', 'hrm.employee-schedule.view'),
  ('SYS_ADMIN', 'hrm.employee-shift.assign'),
  ('SYS_ADMIN', 'hrm.employee.create'),
  ('SYS_ADMIN', 'hrm.employee.import'),
  ('SYS_ADMIN', 'hrm.employee.update'),
  ('SYS_ADMIN', 'hrm.employee.view'),
  ('SYS_ADMIN', 'hrm.leave.approve'),
  ('SYS_ADMIN', 'hrm.leave.self'),
  ('SYS_ADMIN', 'hrm.payroll.calculate'),
  ('SYS_ADMIN', 'hrm.payroll.self'),
  ('SYS_ADMIN', 'hrm.payroll.view'),
  ('SYS_ADMIN', 'hrm.position.create'),
  ('SYS_ADMIN', 'hrm.position.delete'),
  ('SYS_ADMIN', 'hrm.position.update'),
  ('SYS_ADMIN', 'hrm.position.view'),
  ('SYS_ADMIN', 'hrm.shift.create'),
  ('SYS_ADMIN', 'hrm.shift.update'),
  ('SYS_ADMIN', 'hrm.shift.view'),
  ('SYS_ADMIN', 'hrm.work-calendar.create'),
  ('SYS_ADMIN', 'hrm.work-calendar.delete'),
  ('SYS_ADMIN', 'hrm.work-calendar.view'),
  ('SYS_ADMIN', 'lms.book-catalog.manage'),
  ('SYS_ADMIN', 'lms.book-catalog.view'),
  ('SYS_ADMIN', 'lms.document.create'),
  ('SYS_ADMIN', 'lms.document.update'),
  ('SYS_ADMIN', 'lms.document.view'),
  ('SYS_ADMIN', 'lms.exam-question.create'),
  ('SYS_ADMIN', 'lms.exam-question.update'),
  ('SYS_ADMIN', 'lms.exam-question.view'),
  ('SYS_ADMIN', 'lms.exam.assign'),
  ('SYS_ADMIN', 'lms.exam.create'),
  ('SYS_ADMIN', 'lms.exam.delete'),
  ('SYS_ADMIN', 'lms.exam.manage'),
  ('SYS_ADMIN', 'lms.exam.update'),
  ('SYS_ADMIN', 'lms.exam.view'),
  ('SYS_ADMIN', 'lms.exercise-report.manage'),
  ('SYS_ADMIN', 'lms.exercise.create'),
  ('SYS_ADMIN', 'lms.exercise.deadline.confirm'),
  ('SYS_ADMIN', 'lms.exercise.publish'),
  ('SYS_ADMIN', 'lms.exercise.report.export'),
  ('SYS_ADMIN', 'lms.exercise.report.view'),
  ('SYS_ADMIN', 'lms.exercise.update'),
  ('SYS_ADMIN', 'lms.grading.manage'),
  ('SYS_ADMIN', 'lms.grading.view'),
  ('SYS_ADMIN', 'lms.review-video.assign'),
  ('SYS_ADMIN', 'lms.review-video.create'),
  ('SYS_ADMIN', 'lms.review-video.delete'),
  ('SYS_ADMIN', 'lms.review-video.manage'),
  ('SYS_ADMIN', 'lms.review-video.update'),
  ('SYS_ADMIN', 'lms.review-video.view'),
  ('SYS_ADMIN', 'notification.attitude-escalation.approve'),
  ('SYS_ADMIN', 'notification.meeting-invite.approve'),
  ('SYS_ADMIN', 'notification.send.manual'),
  ('SYS_ADMIN', 'permission.audit.view'),
  ('SYS_ADMIN', 'permission.override.delete'),
  ('SYS_ADMIN', 'permission.override.set'),
  ('SYS_ADMIN', 'permission.override.view'),
  ('SYS_ADMIN', 'permission.role.create'),
  ('SYS_ADMIN', 'permission.role.delete'),
  ('SYS_ADMIN', 'permission.role.update'),
  ('SYS_ADMIN', 'permission.role.view'),
  ('SYS_ADMIN', 'report.actual-periods.view'),
  ('SYS_ADMIN', 'report.daily-comment.view'),
  ('SYS_ADMIN', 'report.enrollment-stats.view'),
  ('SYS_ADMIN', 'report.generate'),
  ('SYS_ADMIN', 'report.grade.view'),
  ('SYS_ADMIN', 'report.student-progress.view'),
  ('SYS_ADMIN', 'report.template.create'),
  ('SYS_ADMIN', 'report.template.delete'),
  ('SYS_ADMIN', 'report.template.update'),
  ('SYS_ADMIN', 'report.template.view'),
  ('SYS_ADMIN', 'student.parent.create'),
  ('SYS_ADMIN', 'student.parent.import'),
  ('SYS_ADMIN', 'student.parent.link.create'),
  ('SYS_ADMIN', 'student.parent.link.delete'),
  ('SYS_ADMIN', 'student.parent.update'),
  ('SYS_ADMIN', 'student.parent.view'),
  ('SYS_ADMIN', 'student.profile.create'),
  ('SYS_ADMIN', 'student.profile.import'),
  ('SYS_ADMIN', 'student.profile.update'),
  ('SYS_ADMIN', 'student.profile.view'),
  ('SYS_ADMIN', 'student.status.manage'),
  ('SYS_ADMIN', 'student.transfer.create'),
  ('SYS_ADMIN', 'system.ai-usage.view'),
  ('SYS_ADMIN', 'system.settings.manage'),
  ('SYS_ADMIN', 'system.settings.view'),
  ('SYS_ADMIN', 'task.assign'),
  ('SYS_ADMIN', 'task.manage'),
  ('SYS_ADMIN', 'task.overview.company'),
  ('SYS_ADMIN', 'task.overview.team'),
  ('SYS_ADMIN', 'task.receive'),
  ('SYS_ADMIN', 'user.create'),
  ('SYS_ADMIN', 'user.role.assign'),
  ('SYS_ADMIN', 'user.role.revoke'),
  ('SYS_ADMIN', 'user.role.view'),
  ('SYS_ADMIN', 'user.status.update'),
  ('SYS_ADMIN', 'user.update'),
  ('SYS_ADMIN', 'user.view')
) AS v(role_code, permission_code)
JOIN roles r ON r.code = v.role_code
JOIN permissions p ON p.code = v.permission_code
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- Vai trò mới được đăng nhập
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.code IN ('ACCOUNTANT', 'CONSULTANT') AND p.code = 'auth.login'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- Quản trị viên có mọi quyền; Ban giám đốc thao tác như Quản trị viên (Q4)
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.code IN ('SYS_ADMIN', 'EXECUTIVE') AND p.code <> 'academic.class.manage'
ON CONFLICT (role_id, permission_id) DO NOTHING;
