graph LR
    HocSinh[Học sinh]

    UC01(["UC-01: Đăng nhập hệ thống"])
    UC42(["UC-42: Chọn lớp đang xem"])
    UC13a(["UC-13a: Xem hồ sơ cá nhân"])
    UC23a(["UC-23a: Xem & Theo dõi Kho Video Ôn tập"])
    UC24(["UC-24: Làm bài kiểm tra trực tuyến"])
    UC26(["UC-26: Luyện Nghe - Nói"])
    UC27(["UC-27: Làm bài tập / đề ôn tập"])
    UC62(["UC-62: Phúc khảo điểm"])

    HocSinh --> UC01
    HocSinh --> UC42
    HocSinh --> UC13a
    HocSinh --> UC23a
    HocSinh --> UC24
    HocSinh --> UC26
    HocSinh --> UC27
    HocSinh --> UC62
