graph TD
    PhuHuynh[Phụ huynh]

    UC01(["UC-01: Đăng nhập hệ thống"])
    UC15a(["UC-15a: Nhận thông báo vắng học"])
    UC42(["UC-42: Chọn lớp đang xem"])
    UC25a(["UC-25a: Xem bảng tin Portal"])
    UC25b(["UC-25b: Xem hồ sơ tổng thể từng con"])
    UC30(["UC-30: Xem hóa đơn & thanh toán học phí"])

    PhuHuynh --> UC01
    PhuHuynh --> UC15a
    PhuHuynh --> UC42
    PhuHuynh --> UC25a
    PhuHuynh --> UC25b
    PhuHuynh --> UC30
